# Adapted from https://github.com/seandenigris/Pharo-Enhancements/blob/master/.github/workflows/ci.yaml

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Adapted from https://docs.github.com/en/actions/using-workflows/reusing-workflows
jobs:
  test-and-release:
    uses: seandenigris/Pharo-Enhancements/.github/workflows/ci_reusable.yaml@master
    with:
      project-name: Dynabook